// Flat config. The only rules that matter here are the ones that enforce
// non-negotiable #5: no `any`, no unchecked external input.
import js from "@eslint/js";
import globals from "globals";
import tseslint from "typescript-eslint";

export default tseslint.config(
  {
    ignores: [
      "**/dist/**",
      "**/.next/**",
      "**/node_modules/**",
      "**/coverage/**",
      "artifacts/**",
      "corpus/**",
      ".cache/**",
      // The evald virtualenv ships vendored JavaScript (pip bundles a urllib3
      // emscripten worker). It is not ours and must not be linted.
      "**/.venv/**",
      // Regenerated by `next build` on every run; editing it is pointless and
      // linting it just fails on Next's own triple-slash references.
      "**/next-env.d.ts",
    ],
  },
  js.configs.recommended,
  ...tseslint.configs.recommended,
  {
    rules: {
      "@typescript-eslint/no-explicit-any": "error",
      // Destructuring a value purely to drop it is the clearest way to build a
      // "same env minus one variable" fixture.
      "@typescript-eslint/no-unused-vars": [
        "error",
        { argsIgnorePattern: "^_", varsIgnorePattern: "^_", caughtErrorsIgnorePattern: "^_" },
      ],
      "@typescript-eslint/consistent-type-imports": "error",
      "no-console": ["error", { allow: ["error"] }],
    },
  },
  {
    // Tests may log and may construct deliberately-invalid values.
    files: ["**/*.test.ts", "**/*.test.tsx"],
    rules: { "no-console": "off" },
  },
  {
    /**
     * Build-configuration files run in Node, so Node globals exist.
     *
     * TypeScript sources never hit this: typescript-eslint disables `no-undef`
     * for them, because the compiler already checks it against @types/node. A
     * plain `.mjs` gets `js.configs.recommended` instead, where `no-undef` is on
     * and nothing has told it what `process` is — so reading an environment
     * variable in `next.config.mjs` fails lint while the identical line in a
     * `.ts` file passes.
     */
    // Every .mjs in this repo is a Node ES module: build config, and the example
    // app. Two corrections got us here. The pattern was `*.config.mjs` until a
    // non-config .mjs appeared (D-071), and the globals were hand-listed until
    // the third missing one — `process`, then `Buffer`, then `fetch`. A
    // hand-maintained list of a runtime's globals is a list that is wrong
    // between the day the runtime adds one and the day someone uses it, so this
    // takes the published set instead (D-072).
    files: ["**/*.mjs", "**/*.config.js"],
    languageOptions: { globals: globals.node },
  },
);
